name:                diffs-example
version:             0.1.0.0
github:              "waddlaw/diffs-example"
license:             BSD3
author:              "Shinya Yamaguchi"
maintainer:          "ingroze@gmail.com"
copyright:           "Copyright (c) 2018 Shinya Yamaguchi"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/waddlaw/diffs-example#readme>

dependencies:
- base >= 4.7 && < 5
- incremental
- extensible

library:
  source-dirs: src